version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  #install:
    #Ubuntu 표준 이미지 2.0 이상을 사용하는 경우 런타임 버전을 지정해야 합니다.
    #런타임 버전을 지정하는 경우 Ubuntu 표준 이미지 2.0 이외의 이미지를 사용하면 빌드에 실패합니다.
    #runtime-versions:
      # name: version
      # name: version
    #commands:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      # - command
      # - command
  post_build:
    commands:
      - printf '[{"name":"container_name","imageUri":"%s"}]' 643416288586.dkr.ecr.${region}.amazonaws.com/${family}:latest > imagedefinitions.json
      - sed -i "s|container_name|${cName}|" imagedefinitions.json
      - aws s3 cp s3://${bucketName}/scripts/taskdef.json taskdef.json
      - aws s3 cp s3://${bucketName}/scripts/appspec.yaml appspec.yaml
      - sed -i  "s|exe-role-arn|${exeRoleArn}|" taskdef.json
      - sed -i  "s|task-role-arn|${taskRoleArn}|" taskdef.json
      - sed -i  "s|taskFamily|${family}|" taskdef.json
      - sed -i  "s|\${apm.server}|${apmServer}|" taskdef.json
      - sed -i  "s|\${db.domain}|${dbDomain}|" taskdef.json
      - sed -i  "s|\${db.user}|${dbUser}|" taskdef.json
      - sed -i  "s|\${db.pw}|${dbPw}|" taskdef.json
      - sed -i  "s|\${bucket.name}|${bucketName}|" taskdef.json
      - echo `aws ecs list-task-definitions --status active --output text --sort DESC --family-prefix ${family}` | cut -d ':' -f7 | cut -d ' ' -f1 > last.txt
      - export last_revision=$(cat last.txt)
      - sed -i "s|region|${region}|" appspec.yaml
      - sed -i "s|family|${family}|" appspec.yaml
      - sed -i "s|revision|$((1+$last_revision))|" appspec.yaml
      - sed -i "s|cName|${cName}|" appspec.yaml
      - cat imagedefinitions.json
      - cat taskdef.json
      - cat appspec.yaml
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
artifacts:
  files:
    - imagedefinitions.json
    - taskdef.json
    - appspec.yaml
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths