variables:
  DOCKER_REGISTRY: 643416288586.dkr.ecr.us-east-2.amazonaws.com
  AWS_DEFAULT_REGION: us-east-2
  APP_NAME: chwan-ecr
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

image: maven:3.6.3-openjdk-8

cache:
  paths:
    - .m2/repository/

stages:
  - build
  - test
  - package

maven-build:
  stage: build
  script: "mvn $MAVEN_CLI_OPTS clean package -DskipTests"
  artifacts:
    paths:
      - target/*.jar

maven-test:
  stage: test
  script: "mvn $MAVEN_CLI_OPTS test"


docker-build:
  image: docker:latest
  stage: package
  services:
    - docker:dind
  before_script:
    - apk add --no-cache curl jq python3 py3-pip
    - pip install awscli
    - wget https://github.com/pinpoint-apm/pinpoint/releases/download/v2.3.3/pinpoint-agent-2.3.3.tar.gz
    - aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
    - aws --version
    - docker info
    - docker --version
  script:
    - docker build -t $DOCKER_REGISTRY/$APP_NAME:latest -t $DOCKER_REGISTRY/$APP_NAME:$CI_PIPELINE_IID . 
    - docker push $DOCKER_REGISTRY/$APP_NAME --all-tags
